FROM node:18
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_BUCKET_NAME
ARG AWS_REGION
ARG BREVO_API_KEY
ARG CARD1_REWARD
ARG CARD2_REWARD
ARG CARD3_REWARD
ARG CARD4_REWARD
ARG CONTRACT_ADDRESS
ARG GLL_ADDRESS
ARG DATABASE_URL
ARG GST_VERIFY_URL
ARG IFSC_VERIFY_URL
ARG MY_ENCRYPT_KEY
ARG OPENROUTER_API_KEY
ARG OPENROUTER_URL
ARG REGISTER_REWARD
ARG RPC_URL
ARG TELEGRAM_BOT_TOKEN
ARG DEEPSEEK_API_KEY
ARG OPENAI_API_KEY
ARG FRONTEND_URL
ARG SWITCH
ARG STRIPE_SECRET_KEY

ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
    AWS_REGION=$AWS_REGION \
    BREVO_API_KEY=$BREVO_API_KEY \
    CARD1_REWARD=$CARD1_REWARD \
    CARD2_REWARD=$CARD2_REWARD \
    CARD3_REWARD=$CARD3_REWARD \
    CARD4_REWARD=$CARD4_REWARD \
    CONTRACT_ADDRESS=$CONTRACT_ADDRESS \
    GLL_ADDRESS=$GLL_ADDRESS \
    DATABASE_URL=$DATABASE_URL \
    GST_VERIFY_URL=$GST_VERIFY_URL \
    IFSC_VERIFY_URL=$IFSC_VERIFY_URL \
    MY_ENCRYPT_KEY=$MY_ENCRYPT_KEY \
    OPENROUTER_API_KEY=$OPENROUTER_API_KEY \
    OPENROUTER_URL=$OPENROUTER_URL \
    REGISTER_REWARD=$REGISTER_REWARD \
    RPC_URL=$RPC_URL \
    TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN \
    DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY \
    OPENAI_API_KEY=$OPENAI_API_KEY \
    FRONTEND_URL=$FRONTEND_URL \
    SWITCH=$SWITCH
    STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY


WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 8000
CMD ["npm", "start"]
