name: Deploy to DEV Go-denty

on:
  push:
    branches:
      - lokesh_develop

env:
  AWS_ACCOUNT_ID: 390378708439
  AWS_DEFAULT_REGION: eu-north-1
  IMAGE_REPO_NAME: gll-repo
  IMAGE_TAG: latest
  REPOSITORY_URI: 390378708439.dkr.ecr.eu-north-1.amazonaws.com/gll-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Docker Login
        run: |
          aws ecr get-login-password --region ${{ env.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com

      - name: Docker Build
        run: docker build -t ${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Docker Tag
        run: docker tag ${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }} ${{ env.REPOSITORY_URI }}:${{ env.IMAGE_TAG }}

      - name: Docker Push
        run: docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com/${{ env.IMAGE_REPO_NAME }}:${{ env.IMAGE_TAG }}

      - name: ECS Update
        run: |
          aws ecs update-service \
          --cluster gll-backend  \
          --service gll-backend-service \
          --force-new-deployment \
          --region ${{ env.AWS_DEFAULT_REGION }}
